use movies_db;
/*1*/
SELECT * FROM movies;

/*2*/
SELECT FIRST_NAME, LAST_NAME, RATING FROM actors;

/*3*/
SELECT TITLE AS TITULO FROM SERIES;

/*5*/
SELECT FIRST_NAME, LAST_NAME, RATING FROM actors WHERE RATING > 7.5;

/*6*/
SELECT TITLE,RATING,AWARDS FROM MOVIES WHERE RATING >7.5 AND AWARDS > 2;
 
 /*7*/
SELECT TITLE,RATING FROM MOVIES ORDER BY RATING ASC;
 
 /*8*/
SELECT * FROM MOVIES LIMIT 3;

/*9*/
SELECT * FROM MOVIES ORDER BY RATING DESC LIMIT 5;

/*10*/
SELECT * FROM MOVIES ORDER BY RATING DESC LIMIT 5 , 5;

/*11*/
SELECT * FROM actors LIMIT 10;

/*12*/
SELECT * FROM actors LIMIT 10 OFFSET 20;

/*13*/
SELECT * FROM actors LIMIT 10 OFFSET 50;

/*14*/
SELECT TITLE,RATING FROM MOVIES WHERE TITLE = 'Toy Story';

/*15*/
SELECT * FROM ACTORS WHERE FIRST_NAME LIKE 'Sam%';

/*16*/
SELECT * FROM MOVIES WHERE RELEASE_DATE BETWEEN STR_TO_DATE("2004", "%Y") AND STR_TO_DATE("2008", "%Y");

/*17*/
SELECT * FROM MOVIES WHERE RATING > 3 AND AWARDS > 1 AND RELEASE_DATE BETWEEN STR_TO_DATE("1988", "%Y") AND STR_TO_DATE("2009", "%Y") ORDER BY RATING;

/*18*/
SELECT * FROM MOVIES WHERE RATING > 3 AND AWARDS > 1 AND RELEASE_DATE BETWEEN STR_TO_DATE("1988", "%Y") AND STR_TO_DATE("2009", "%Y") ORDER BY RATING LIMIT 10,3;

