-- MySQL Script generated by MySQL Workbench
-- Tue Jun 22 12:39:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamento` (
  `departamento_id` INT NOT NULL,
  `departamento_nombre` VARCHAR(45) NULL,
  `departamento_direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`departamento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `empleado_num_legajo` INT NOT NULL,
  `empleado_dni` INT NULL,
  `empleado_apellido` VARCHAR(45) NULL,
  `empleado_nombre` VARCHAR(45) NULL,
  `empleado_fecha_nac` DATETIME NULL,
  `empleado_fecha_incorporacion` DATETIME NULL,
  `empleado_cargo` VARCHAR(45) NULL,
  `empleado_sueldo_neto` DECIMAL(10) NULL,
  `departamento_departamento_id` INT NOT NULL,
  PRIMARY KEY (`empleado_num_legajo`),
  INDEX `fk_empleado_departamento_idx` (`departamento_departamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_departamento`
    FOREIGN KEY (`departamento_departamento_id`)
    REFERENCES `mydb`.`departamento` (`departamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargo` (
  `cargo_id` INT NOT NULL,
  `cargo_nombre` VARCHAR(45) NULL,
  `cargo_fecha_inicio` DATETIME NULL,
  `cargo_fecha_fin` DATETIME NULL,
  `cargo_departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`cargo_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
