server:
  port: 8080

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ml_app_user1
#    password: ml_app_user1
#    url: jdbc:mysql://localhost:3306/ml_app_consultorio?useUnicode=yes&characterEncoding=UTF-8
#
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    defer-datasource-initialization: true
#    open-in-view: false
#    hibernate:
#      ddl-auto: create-drop
#
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql


#H2
spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: admim
    password: admin

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  #spring.jpa.hibernate.ddl-auto=update
  #spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
  #spring.h2.console.enabled=true
  #spring.datasource.driverClassName=org.h2.Driver
  #spring.datasource.url=jdbc:h2:mem:testdb
  #spring.datasource.username=admin
  #spring.datasource.password=admin
